# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb_activerecord}
  s.version = "1.1.1"

  s.authors = [%q{Duane Johnson}]
  s.date = %q{2011-06-20}
  s.description = %q{Merb plugin that provides ActiveRecord support}
  s.email = %q{canadaduane@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  s.homepage = %q{http://github.com/merb/merb_activerecord}
  s.rdoc_options = [%q{--charset=UTF-8}]
  s.require_paths = [%q{lib}]
  s.summary = %q{This plugin allows seamless integration of the ActiveRecord ORM with merb}

  s.add_dependency 'merb-core', '~> 1.1.3'
  s.add_dependency 'activerecord', '>= 3.0.7'

  s.add_development_dependency 'bundler', '~> 1.10'
  s.add_development_dependency 'rake', '~> 10.0'
  s.add_development_dependency 'rspec', '>= 1.2.9'
end
